probes:
  - ProbeName: 'inside'
    ProbeaAddress: 'http://192.168.4.94'
  - ProbeName: 'outside'
    ProbeaAddress: 'http://192.168.4.135'
interval: 1
number_of_intervals: 3
filename: 'testFile.xlsx'
