name: Build and Upload Go Binary

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
      run: |
        cd app
        mkdir -p build
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o build/my-app-${{ matrix.os }}-${{ matrix.arch }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: go-binaries
        path: build/